version: "3"

services:
  wunderground:
    build: ./
    image: cfei/weather-station-driver
    container_name: weather_station_driver
    environment:
      WEATHERSTDR_WUND_API_KEY: YourKey
      WEATHERSTDR_INITIAL_SUBSCRIPTIONS: StationId=IODENS3;Interval=5,StationId=IKASTR4;Interval=10

    