version: "3"

services:
  wunderground:
    build: ./
    image: cfei/weather-station-driver
    container_name: weather_station_driver
    environment:
      WEATHERSTDR_WUND_API_KEY: YourKey
      WEATHERSTDR_INITIAL_SUBSCRIPTIONS: StationId=I83ODENS10;Interval=60|GeoCode=55.40,10.38;Interval=60